### ISSUE TITLE
Build process 

### ISSUE THREAD

**Issue by netmindz** [wled-install/wled-install.github.io#2]
How are you creating the binaries? Would it not be better to have this project have GitHub actions that handle the creation of the binaries?

**Comment by netmindz** [comment]
Looks like we can trigger cross-repo workflows https://github.com/orgs/community/discussions/26323

**Comment by wled-install** [comment]
I compile binaries manually after some code review. Well, technically, sure, it is possible to compile automatically from other repo or use bins build by others. However, since they are then published on my github web page I have to ensure there is no harmful code inside according to german/EU regulatioins and currently I can only rely on manual review.

**Comment by netmindz** [comment]
What is the best way for the projects you are building to notify you of new releases?

**Comment by wled-install** [comment]
Email to info @ myhome-control.de

**Comment by wled-install** [comment]
I've introduced nightly builds for MoonModules version with an additional note that it is not tested. Will extend to AC and SR later
