### ISSUE TITLE
Add MoonModules binaries for other ESP32 variants

### ISSUE THREAD

**Issue by jamesmyatt** [wled-install/wled-install.github.io#4]
There are now ESP32-c3, -s2, -s3 variants of the MM firmware. Can you add them here, please?

**Comment by wled-install** [comment]
I've added some -c3, -s2, -s3 variants. The issue is, however, that there are lots of different  -c3, -s2, -s3 boards that require their special settings during compile. That means the files I va ecompiled might not fit to your board.

if you want easy and working wled, use standart ESP32. If you want -c3, -s2, -s3, consider to install VSC and compile yourself. Or use https://wled-compile.github.io/ to compile on github (using moonmodules repo or clone it, make changes and use it)

**Comment by jamesmyatt** [comment]
Thanks. I hadn't seen https://wled-compile.github.io/ .
